name: Unified CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [opened, closed, review_requested]
  schedule:
    - cron: '0 0 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Build the project
        run: go build -v -o mi-proyecto .

      - name: List files in the repository
        run: ls -la

      - name: Show latest commits
        run: git log -5 --oneline

      - name: Show all contributors
        run: git shortlog -s -n

      # Enviar evento a la API cuando se abre un Pull Request (de CI/CD Pipeline)
      - name: Send PR Opened Event to API
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          curl -X POST https://adb3-187-244-123-22.ngrok-free.app/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "${{ github.event.repository.full_name }}",
              "type": "${{ github.event_name }}",
              "action": "${{ github.event.action }}",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "commit_id": "${{ github.sha }}",
              "user": "${{ github.event.sender.login }}",
              "branch": "${{ github.head_ref || github.ref_name }}"
            }'

      # Enviar evento a la API cuando se solicita revisión en un PR (de CI/CD Pipeline)
      - name: Send PR Review Requested Event to API
        if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
        run: |
          curl -X POST https://adb3-187-244-123-22.ngrok-free.app/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "${{ github.event.repository.full_name }}",
              "type": "${{ github.event_name }}",
              "action": "${{ github.event.action }}",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "commit_id": "${{ github.sha }}",
              "user": "${{ github.event.sender.login }}",
              "branch": "${{ github.head_ref || github.ref_name }}"
            }'

      # Enviar evento a la API cuando se mergea un PR (de CI/CD Pipeline)
      - name: Send PR Merged Event to API
        if: github.event.pull_request.merged == true
        run: |
          curl -X POST https://adb3-187-244-123-22.ngrok-free.app/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "${{ github.event.repository.full_name }}",
              "type": "${{ github.event_name }}",
              "action": "merged",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "commit_id": "${{ github.sha }}",
              "user": "${{ github.event.sender.login }}",
              "branch": "${{ github.head_ref || github.ref_name }}"
            }'

      # Enviar evento a la API cuando hay un nuevo Push (de CI/CD Pipeline)
      - name: Send Push Event to API
        if: github.event_name == 'push'
        run: |
          curl -X POST https://adb3-187-244-123-22.ngrok-free.app \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "${{ github.event.repository.full_name }}",
              "type": "${{ github.event_name }}",
              "action": "push",
              "commit_id": "${{ github.sha }}",
              "user": "${{ github.event.sender.login }}",
              "branch": "${{ github.ref_name }}"
            }'

      # Enviar evento a la API cuando las pruebas pasan con éxito (de CI/CD Pipeline)
      - name: Send Tests Passed Event to API
        if: success()
        run: |
          curl -X POST https://adb3-187-244-123-22.ngrok-free.app/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "${{ github.event.repository.full_name }}",
              "type": "tests",
              "action": "passed",
              "commit_id": "${{ github.sha }}",
              "user": "${{ github.event.sender.login }}",
              "branch": "${{ github.ref_name }}"
            }'
